apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: flux-system
spec:
  targetNamespace: media
  releaseName: homepage
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "5.0.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest
            env:
              HOMEPAGE_ALLOWED_HOSTS: "home.home.lab"
            resources:
              requests: { cpu: 100m, memory: 128Mi }
              limits: { cpu: 500m, memory: 512Mi }

    service:
      main:
        ports:
          main:
            port: 3000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: home.home.lab
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: main

    persistence:
      config:
        enabled: true
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
