apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage/storageclasses.yaml
  - storage/mediapvc.yaml
  - monitoring/ingress.yaml
  - monitoring/app-ingress/grafana-ingress.yaml
  - syncthing/syncthing-namespace.yaml
  - sources/helmrepository-csi-driver-nfs.yaml
  - csi-driver-nfs/helmrelease.yaml
  - sources/helmrepository-ingress-nginx.yaml
  - ingress-nginx/helmrelease.yaml
