apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  targetNamespace: monitoring
  releaseName: loki
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "7.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      useTestSchema: true
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: nfs-cluster
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
