apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/helmrepository-bjws.yaml
  - sources/helmrepository-portainer.yaml
  - portainer/helmrelease.yaml
  - jellyfin/helmrelease.yaml
  - radarr/helmrelease.yaml
  - sonarr/helmrelease.yaml
  - prowlarr/helmrelease.yaml
  - qbittorrent/helmrelease.yaml
  - flaresolverr/helmrelease.yaml
  - splunk/helmrelease.yaml
  - navidrome/helmrelease.yaml
  - sources/helmrepository-immich.yaml
  - immich-postgres/helmrelease.yaml
  - immich/helmrelease.yaml
  - lidarr/helmrelease.yaml
  - beets/helmrelease.yaml
